version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A django_celery_redis worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
